src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Allocated_Budget__c</fullName>
        <label>Allocated Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Spent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Budget Spent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Remaining_Budget__c</fullName>
        <formula>Allocated_Budget__c - Budget_Spent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>Budget # - {0000}</displayFormat>
        <label>Budget Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Material__c.object
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Material_Name__c</fullName>
        <formula>Material__r.Name</formula>
        <label>Material Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Quantity__c * List_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Transaction {0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ManagerViewController.cls
/**
 * Created by ConorOliver on 8/14/2017.
 */
public with sharing class ManagerViewController {

    public String selectedEmployee{ get;set; }
    public List<User> employees{ get;set; }

    public List<Budget__c> employeeBudget{ get; set; }
    public List<Transaction__c> employeeTransactions{ get; set; }

    public Id userId;
    public Boolean displayEmployees{ get; set; }
    public Boolean noEmployees { get; set; }

    public Boolean renderTable{ get; set; }




    /***
    Gets the current user id and selects all users that have current user as manager
    **/
    public ManagerViewController() {
        //In order to get every user in the hierarchy below the current user, we need to use a queue
        //All users with current user as manager are added to the queue, then their children are, and so forth
        List<User> employeeSearchQueue = new List<User>();
        userId = UserInfo.getUserId();
        User pageUser = [Select id, Name from User where Id = :userId];
        employeeSearchQueue.add(pageUser);
        employees = new List<User>();
        while(employeeSearchQueue.size() != 0) {
            employees.add(employeeSearchQueue.get(0));
            List<User> managedEmployees = [SELECT Id, Name FROM User WHERE ManagerId = :employeeSearchQueue.get(0).Id];
            employeeSearchQueue.remove(0);
            if(managedEmployees != null) {
                for (User u : managedEmployees) {
                    employeeSearchQueue.add(u);
                }
            }
        }
        noEmployees = False;
        renderTable = False;
        displayEmployees = True;
        if (employees == null || employees.size() == 0) {
            displayEmployees = False;
            noEmployees = True;
        }
    }

    /***
    This is called when the user clicks on an employee. It sets the current budget to display as well as
    the transaction history for that user.
    **/
    public void populateTable() {
        renderTable = True;
        employeeBudget = [SELECT Id, Name, Allocated_Budget__c, Budget_Spent__c, Remaining_Budget__c FROM
        Budget__c WHERE User__r.Name = :selectedEmployee];

        employeeTransactions = [SELECT Id, Total_Price__c, Transaction_Date__c, Material__c, Material_Name__c,
                Quantity__c FROM Transaction__c WHERE User__r.Name = :selectedEmployee];

    }
}