src/objects/Material__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Laptop</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Transaction {0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/transactionOrderPrototypeTest.cls
@isTest
private class transactionOrderPrototypeTest {
	
	@testSetup
	private static void addDummyMaterial(){
		Material__c dummyMaterial = new Material__c(
										Name__c = 'Dummy',
										Category__c = 'Laptop',
										Price__c = 15
										);
		insert dummyMaterial;
	}
	
    @isTest
    private static void testFunctions(){
    	transactionOrderPrototypeController testController = new transactionOrderPrototypeController();
    	Material__c dummyMaterial = [SELECT Name__c, Category__c, Price__c, Id FROM Material__c WHERE Name__c = 'Dummy'];
    	testController.newTransaction.Material__c = dummymaterial.Id;
    	testController.newTransaction.Quantity__c = 3;
    	Decimal testTotal = testController.getTotal();
    	Decimal testPrice = testController.getPrice();
    	testController.saveTransaction();
    	System.AssertEquals(15, testPrice);
    	System.AssertEquals(15*3, testTotal);
    	Transaction__c insertedTransaction = [SELECT Material__c FROM Transaction__c WHERE Material__c = :dummyMaterial.Id];
    	System.Assert(insertedTransaction != NULL);
    }
}