src/objects/Material__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Transaction {0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/transactionOrderExt.cls
public with sharing class transactionOrderExt {
    public Transaction__c newTransaction{get;set;}
    private Map<Id, Material__c> allMaterials;
    
    public transactionOrderExt(ApexPages.StandardController stdController){
        newTransaction = new Transaction__c(Quantity__c = 1,
                                            User__c = UserInfo.getUserId(),
                                            Transaction_Date__c = date.today()
                                            );
        allMaterials = new Map<Id, Material__c>([SELECT Price__c FROM Material__c]);
        
    }
    
    public Decimal getTotal(){
        Decimal materialPrice = 0;
        if(newTransaction.Material__c!=NULL){
            materialPrice = allMaterials.get(newTransaction.Material__c).Price__c;
        }
        return newTransaction.Quantity__c * materialPrice;
    }
    
    public Decimal getPrice(){
        Decimal price = 0;
        if(newTransaction.Material__c != NULL){
            price = allMaterials.get(newTransaction.Material__c).Price__c;
        }
        return price;
    }
    
    public pageReference saveTransaction(){
        try{
        	insert newTransaction;
        	return new pageReference('/' + newTransaction.Id);
    	}catch(TransactionTriggerHandlerException e){
    		//ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'The transaction was not saved. The current user has no budget available. Error: ' + e.getMessage()));
    	}catch(Exception e){
    		//ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'There was an error saving the transaction: ' + e.getMessage()));
    	}
        return NULL;
    }
}