src/objects/Material__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Laptop</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DisplayMaterialsContoller.cls
public with sharing class DisplayMaterialsContoller {

    public String Price { get; set; }

    public String MaterialName { get; set; }
    //public string Name__c{get;set;}
    //public string 
    //string[] materials = new string;
    public list<Integer> quantity{get;set;}
    public list<Material__c> materialsList{get;set;}
    
    public DisplayMaterialsContoller () {
        materialsList = [select Name__c, Price__c, Category__c from Material__c];
        /*
        for(Integer i=1; i<11; i++) {
            quantity.add(i);
        }*/
        
    }
}