src/objects/Material__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Transaction {0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/bulkTransactionPrototypeController.cls
public with sharing class bulkTransactionPrototypeController {
    public List<Transaction__c> newTransactions{get;set;}
    public List<Decimal> newTotals{get;set;}
    public List<String> chosenMaterialNames{get;set;}
    public List<Decimal> chosenMaterialPrice{get;set;}
    public Decimal totalCost{get;set;}
    
    private Map<Id, Material__c> allMaterials;
    
    public bulkTransactionPrototypeController(){
    	
    	newTransactions = new List<Transaction__c>{new Transaction__c(Quantity__c = 0,
    																	User__c = UserInfo.getUserId()
    																	)};
		allMaterials = new Map<Id, Material__c>([SELECT Name__c, Price__c FROM Material__c]);
    }
    
    public void addTransaction(){
    	newTransactions.add(new Transaction__c(Quantity__c = 0,
												User__c = UserInfo.getUserId()
												));
    }
    
    public void updateRow(){
    	totalCost = 0;
    	Decimal transactionCost = 0;
    	newTotals = new List<Decimal>();
    	chosenMaterialNames = new List<String>();
    	chosenMaterialPrice = new List<Decimal>();
    	for(Transaction__c curTransaction:newTransactions){
    		transactionCost = curTransaction.Quantity__c * allMaterials.get(curTransaction.Material__c).Price__c;
    		newTotals.add(transactionCost);
    		totalCost = totalCost + transactionCost;
    		chosenMaterialNames.add(allMaterials.get(curTransaction.Material__c).Name__c);
    		chosenMaterialPrice.add(allMaterials.get(curTransaction.Material__c).Price__c);
    	}
    }
    
    public pageReference saveTransactions(){
        insert newTransactions;
        return NULL;
    }
}